import type { Metadata } from 'next'

import '../../public/assets/css/app.min.css'
import '../../public/assets/css/bootstrap.min.css'
import '../../public/assets/css/custom.min.css'
import '../../public/assets/css/icons.min.css'

import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<head>
				{/* <link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="anonymous"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
					rel="stylesheet"
				/> */}
			</head>
			<body>
				<div id="layout-wrapper">
					<div className='app-menu navbar-menu'>
						
					</div>
					<main className="main-content">{children}</main>
				</div>
			</body>
		</html>
	)
}
