import Head from "next/head";
import { Inter } from "next/font/google";
import { metadata } from "variables";
import HomeHero from "@/components/pages/home/HomeHero";
import HomeJoinNetwork from "@/components/pages/home/HomeJoinNetwork";
import HomeNumbers from "@/components/pages/home/HomeNumbers";
import HomeFAQ from "@/components/pages/home/HomeFAQ";
import HomeStartProject from "@/components/pages/home/HomeStartProject";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { title } = metadata;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHero />
      <HomeJoinNetwork />
      <HomeNumbers />
      <HomeStartProject />
      <HomeFAQ />
    </>
  );
}
