import { useCreateSkillMutation, useUpdateSkillMutation } from '@/redux/services/skill.services'
import { SkillData } from '@/types/option.types'
import { generateSlug } from '@/utils/text.utils'
import {
	Button,
	Modal,
	ModalBody,
	ModalCloseButton,
	ModalContent,
	ModalHeader,
	ModalOverlay,
	useToast,
} from '@chakra-ui/react'
import React, { useEffect, useState } from 'react'

type Props = {
	isOpen: boolean
	onClose: (data?: SkillData, isUpdate?: boolean) => void
	skillData?: SkillData | null
}

export default function AddSkillPopup({ isOpen, onClose, skillData }: Props) {
	const [name, setName] = useState(skillData?.name || '')
	const [slug, setSlug] = useState(skillData?.slug || '')
	const [icon_url, setIconURL] = useState(skillData?.icon_url || '')
	const [createSkill, { isLoading, error, data }] = useCreateSkillMutation()
	const [
		updateSkill,
		{ isLoading: updateLoading, error: updateError, data: updatedData },
	] = useUpdateSkillMutation()
	const toast = useToast()

	const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
		const newName: string = e.target.value
		setName(newName)

		const newSlug: string = generateSlug(newName)
		setSlug(newSlug)
	}

	const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault()

		let data = {
			// slug: slug?.trim(),
			name,
			icon_url,
		}
		if (!name || !slug || !icon_url) {
			return toast({ status: 'info', title: name + ' Created' })
		}

		createSkill(data)
		setName('')
		setSlug('')
	}

    const handleUpdate = async (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();

		let data = {
			name,
			icon_url,
		}

		if (!name || !slug || !icon_url) {
			return toast({ status: 'info', title: name + ' Created' })
		}

		updateSkill({data, id: skillData?._id })
    }

	useEffect(() => {
		if (error) {
			//@ts-ignore
			toast({
				status: 'error',
				//@ts-ignore
				title: error?.data?.message || 'Error, please try again.',
			})
		}
		if (data) {
			onClose(data)
			toast({ status: 'success', title: 'Skill created' })
			return
		}
		if(updatedData){
			onClose(updatedData, true)
			toast({ status: 'success', title: 'Skill updated' })
			return
		}
		if (updateError) {
			//@ts-ignore
			toast({
				status: 'error',
				//@ts-ignore
				title: updateError?.data?.message || 'Error, please try again.',
			})
		}
	}, [error, data, updateError, updatedData])

	return (
		<Modal isOpen={isOpen} onClose={onClose} size={'lg'}>
			<ModalOverlay />
			<ModalContent>
				<ModalHeader>{skillData ? `Edit Skill` : `Create Skill`}</ModalHeader>
				<ModalCloseButton />
				<ModalBody>
					<div className="live-preview">
						<form onSubmit={skillData ? handleUpdate : onSubmit}>
							<div className="row">
								<div className="col-md-12">
									<div className="mb-3">
										<label htmlFor="skill-name" className="form-label">
											Name
										</label>
										<input
											required
											type="text"
											className="form-control"
											placeholder="React, Angular, Photoshop, Power BI etc."
											id="skill-name"
											value={name}
											onChange={handleNameChange}
										/>
									</div>
								</div>
								<div className="col-md-12">
									<div className="mb-3">
										<label htmlFor="slug" className="form-label">
											Slug{' '}
											<small className="text-muted fw-light">
												Autogenerate
											</small>
										</label>
										<input
											required
											type="text"
											className="form-control"
											placeholder="Autogenerated Slug"
											id="slug"
											disabled
											value={slug}
										/>
									</div>
								</div>
								<div className="col-md-12">
									<div className="mb-3">
										<label htmlFor="icon-url" className="form-label">
											Image URL
										</label>
										<input
											required
											type="text"
											className="form-control"
											placeholder="URL from the internet"
											id="icon-url"
											value={icon_url}
											onChange={(e) => setIconURL(e.target.value)}
										/>
									</div>
								</div>
							</div>
							<hr className="text-muted" />
							<Button
								colorScheme="green"
								width="full"
								type="submit"
								mb="3"
								isLoading={isLoading || updateLoading}
							>
								Create
							</Button>
						</form>
					</div>
				</ModalBody>
			</ModalContent>
		</Modal>
	)
}
